version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio_v1
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - nifi-minio-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nifi:
    image: streamlio/nifi:latest
    container_name: nifi_streamlio
    ports:
      - "8080:8080"  # Web UI
      - "8443:8443"  # Secure Web UI (not configured in this example)
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_CLUSTER_ADDRESS=localhost
      - NIFI_REMOTE_INPUT_HOST=
    volumes:
      - nifi_data:/opt/nifi/nifi-current
      - /home/sfaxi/test/facture:/data
      - /home/sfaxi/test/spark/jars:/external_jars
      - /home/sfaxi/test/scripts:/scripts
    networks:
      - nifi-minio-net
    depends_on:
      minio:
        condition: service_healthy
       
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-m
    ports:
      - "8082:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master internal communication
      - "4040:4040"  # Spark Application UI
    environment:
      - SPARK_MODE=master
    volumes:
      - /home/sfaxi/test/scripts:/scripts
      - /home/sfaxi/test/spark/jars:/external_jars
    networks:
      - nifi-minio-net

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-w
    ports:
      - "8081:8081"  # Spark Worker Web UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - nifi-minio-net
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    container_name: postgres_db1
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflowdb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
    - nifi-minio-net
    
volumes:
  minio_data:
    driver: local
  nifi_data:
    driver: local

networks:
  nifi-minio-net:
    driver: bridge